# Generated by Django 3.2.8 on 2021-10-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="breaking",
            field=models.BooleanField(default=False, verbose_name="Срочная новость"),
            preserve_default=False,
        ),
    ]
